version: '3'
services:
  web-gym:
    container_name: web-gym
    build: 
      context: ../../../
      dockerfile: Lab.Gym.Web/Docker/Production/Dockerfile
    ports: 
      - "5002:8080"
    networks:
      - pgsqlnet
    restart: unless-stopped 
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
        ASPNETCORE_ENVIRONMENT: Production
networks:
  pgsqlnet:
    name: tulip-net
    external: true