version: '3'
services:
  web-gym:
    container_name: web-gym
    build: 
      context: ../../../
      dockerfile: Lab.Gym.Web/Docker/Local/Dockerfile
    ports: 
      - "5002:8080"
    networks:
      - tulip-net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerLocal
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_HTTPS_PORT=5002
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=123
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    # volumes:
    #   - ~/.aspnet/https:/https:ro
networks:
  tulip-net:
    name: tulip-net
    external: true